version: "3.8"
services:
  mongo:
    image: mongo:6
    container_name: nest-mongo1
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  mailhog:
    image: mailhog/mailhog
    container_name: nest-mailhog1
    restart: always
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
